server:
  servlet:
    context-path: /system
  port: 10001

spring:
  profiles:
    active: dev
  application:
    name: ljun51-system

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.ljun51.system.model